name: task_flow
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_bloc: ^9.1.1
  lottie: ^3.3.1
  google_nav_bar: ^5.0.7
  uuid: ^4.5.1
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6


flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - shorebird.yaml
  #   - images/a_dot_ham.jpeg
